before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    binary: registrygen
    main: ./main.go
    ldflags: -X github.com/pulumi/registrygen/pkg/version.Version={{.Version}}
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  prerelease: auto
brews:
  -
    name: registrygen
    tap:
      owner: pulumi
      name: homebrew-tap
    commit_author:
      name: pulumi-bot
      email: bot@pulumi.com
    homepage: "https://pulumi.io"
    description: "Creation of Pulumi Package Metadata and API Docs for use in the Pulumi Registry"
    folder: Formula
    license: Apache-2.0
    test: |
      system "#{bin}/registrygen help"
